SELECT BEASTS.NAME, count(DISTINCT CONTINENTS.ROWI) AS how_many_Cont FROM BEASTS 
INNER JOIN ENCOUNTERS ON BEASTS.ROWI = ENCOUNTERS.BEAST
INNER JOIN PLACES ON ENCOUNTERS.PLACE = PLACES.ROWI
INNER JOIN CONTINENTS ON  PLACES.CONT = CONTINENTS.ROWI
GROUP BY BEASTS.NAME
HAVING how_many_Cont > 1
ORDER BY BEASTS.NAME